---

- name: Configuring nginx
  template: >
    src=etc-nginx-nginx.conf.j2
    dest=/etc/nginx/nginx.conf
    owner=root
    group=root
    mode=644
  notify: reload nginx
  tags:
    - web
    - nginx

