---

- import_tasks: install.yml
  tags:
    - web
    - nginx
    - install
    - nginx-install

- import_tasks: config.yml
  tags:
    - web
    - nginx
    - config
    - nginx-config

- import_tasks: manage-sites.yml
  when: nginx_sites | length
  tags:
    - web
    - nginx
    - manage
    - nginx-manage
    - nginx-manage-sites

- import_tasks: manage-proxies.yml
  when: nginx_proxies | length
  tags:
    - web
    - nginx
    - manage
    - nginx-manage
    - nginx-manage-proxies

- import_tasks: service.yml
  tags:
    - web
    - nginx
    - service
    - nginx-service
